apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-frontend
spec:
  selector:
    app: expense-tracker-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort