apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-frontend
  labels:
    app: expense-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-frontend
    spec:
      containers:
      - name: frontend
        image: ogudaarnold/expense-tracker-frontend:v1.1
        ports:
        - containerPort: 80