apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-frontend
  labels:
    app: expense-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-frontend
  template:
    metadata:
      labels:
        app: expense-tracker-frontend
    spec:
      containers:
      - name: frontend
        image: ogudaarnold/expense-tracker-frontend:v1.3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"