apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded "postgres"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded "password"
  POSTGRES_DB: ZXhwZW5zZV90cmFja2Vy  # Base64 encoded "expense_tracker"