apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-role-binding
subjects:
  - kind: ServiceAccount
    name: loki
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: loki-role
  apiGroup: rbac.authorization.k8s.io
