apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 1000
      containers:
      - name: loki
        image: grafana/loki:3.1.0
        ports:
        - containerPort: 3100
        args:
        - -config.file=/etc/loki/loki-config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki
        - name: chunks-volume
          mountPath: /loki/chunks
        - name: compactor-volume
          mountPath: /loki/compactor
        - name: wal-volume
          mountPath: /loki/wal
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: config-volume
        configMap:
          name: loki-config
      - name: chunks-volume
        emptyDir: {}
      - name: compactor-volume
        emptyDir: {}
      - name: wal-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
      chunk_idle_period: 5m
    schema_config:
      configs:
      - from: 2020-10-24
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
    storage_config:
      filesystem:
        directory: /loki/chunks
      tsdb_shipper:
        active_index_directory: /loki/chunks/active
        cache_location: /loki/chunks/cache
    compactor:
      working_directory: /loki/compactor
    limits_config:
      retention_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    memberlist:
      join_members:
      - loki:3100