apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: expense-tracker-db
  labels:
    app: expense-tracker-db
spec:
  serviceName: expense-tracker-db
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-db
  template:
    metadata:
      labels:
        app: expense-tracker-db
    spec:
      containers:
      - name: db
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: expense-tracker-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: expense-tracker-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: expense-tracker-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: pvc-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
  volumeClaimTemplates:
  - metadata:
      name: pvc-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: hostpath