apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-db
  labels:
    app: expense-tracker-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-db
  template:
    metadata:
      labels:
        app: expense-tracker-db
    spec:
      containers:
      - name: db
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: expense-tracker-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: expense-tracker-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: expense-tracker-secret
              key: POSTGRES_DB
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # - name: POSTGRES_PASSWORD
        #   value: "password"
        # - name: POSTGRES_DB
        #   value: "expense_tracker"