apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: expense-tracker-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath