apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-api
spec:
  selector:
    app: expense-tracker-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP