name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout Code
        uses: actions/checkout@v3

      - name:  Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set kubeconfig for Cloud
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CLOUD }}" > ~/.kube/config

      - name: Deploy YAMLs 
        run: |
          kubectl apply -f db/
          kubectl apply -f config_secrets/
          kubectl apply -f api/
          kubectl apply -f frontend/
          kubectl apply -f monitoring/
