name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Apply Kubernetes Manifests
      run: |
        kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f config_secrets/
        kubectl apply -f db/
        kubectl apply -f api/
        kubectl apply -f frontend/
        kubectl apply -f monitoring/
